# Generated by Django 5.2 on 2025-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Reader', 'reader'), ('Admin', 'admin'), ('Publisher', 'publisher')], default='Reader', max_length=15),
        ),
    ]
