# Generated by Django 5.2 on 2025-06-10 13:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expire_date',
            field=models.DateTimeField(default=accounts.models.check_date),
        ),
    ]
